services:
  web:
    image: simiodev/simiomath-web:latest
    # Para los que quieran construir localmente la imagen
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
    restart: unless-stopped
